<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $param = [
            [
                'kid_name' => '中山功太',
                'category' => '集団行動',
                'title' => '着席する',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '集団行動',
                'title' => '静かに聞く',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '集団行動',
                'title' => '注目する',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '集団行動',
                'title' => '集団参加',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '集団行動',
                'title' => '流れに沿って動く',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '集団行動',
                'title' => '手順に沿って動く',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '集団行動',
                'title' => '指示理解',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '集団行動',
                'title' => '指示に従う',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '集団行動',
                'title' => 'ルール理解',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '集団行動',
                'title' => 'ルールに従う',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '集団行動',
                'title' => '役割遂行',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '集団行動',
                'title' => '役割分担',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '集団行動',
                'title' => '協力する',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '集団行動',
                'title' => '貸し借り',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '集団行動',
                'title' => '道具の共有',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '集団行動',
                'title' => '順番交代',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '集団行動',
                'title' => '役割交代',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '集団行動',
                'title' => '見通しをもつ',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '集団行動',
                'title' => '計画を立てる',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '集団行動',
                'title' => '企画・実行',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => 'セルフコントロール',
                'title' => '勝ち負けの経験',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => 'セルフコントロール',
                'title' => '負けの受け入れ',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => 'セルフコントロール',
                'title' => '失敗の受け入れ',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => 'セルフコントロール',
                'title' => '注意集中',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => 'セルフコントロール',
                'title' => '衝動性の制御',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => 'セルフコントロール',
                'title' => '行動調整',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => 'セルフコントロール',
                'title' => '気持ちの切り替え',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => 'セルフコントロール',
                'title' => '感情の認知',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => 'セルフコントロール',
                'title' => '感情の表現',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => 'セルフコントロール',
                'title' => 'こだわりへの対処',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => 'セルフコントロール',
                'title' => '柔軟に対処する',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => 'セルフコントロール',
                'title' => '折り合いをつける',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '社会的認知',
                'title' => 'ジャイアントアテンション',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '社会的認知',
                'title' => '相手の動きに合わせる',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '社会的認知',
                'title' => '他社の視点に立つ',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '社会的認知',
                'title' => '心の理論',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '社会的認知',
                'title' => '対人ルールの理解',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '社会的認知',
                'title' => '社会的問題の解決',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '仲間関係',
                'title' => '名前を覚える',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '仲間関係',
                'title' => '仲間のことを知る',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '仲間関係',
                'title' => '仲間にかかわる',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '仲間関係',
                'title' => '所属感を高める',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '仲間関係',
                'title' => '遊びの共有',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '仲間関係',
                'title' => '道具の共有',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '仲間関係',
                'title' => '仲間を応援する',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '仲間関係',
                'title' => '仲間を援助する',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => 'コミュニケーション',
                'title' => '情報の伝達',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => 'コミュニケーション',
                'title' => '情報の聞き取り',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => 'コミュニケーション',
                'title' => '伝言をする',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => 'コミュニケーション',
                'title' => 'ホウレンソウ',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => 'コミュニケーション',
                'title' => '依頼する',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => 'コミュニケーション',
                'title' => '質問・応答のルール',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => 'コミュニケーション',
                'title' => '言葉のやりとり',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => 'コミュニケーション',
                'title' => '会話のやりとり',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => 'コミュニケーション',
                'title' => '話し合い',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '生活',
                'title' => '買い物のマナー',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '生活',
                'title' => '電話のマナー',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '生活',
                'title' => '金銭管理',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '生活',
                'title' => '公共のマナー',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '生活',
                'title' => '社会的資源の活動',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '自己・情緒',
                'title' => '達成感',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '自己・情緒',
                'title' => '自己表現',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '自己・情緒',
                'title' => '自己理解',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '自己・情緒',
                'title' => '自己の振り返り',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '自己・情緒',
                'title' => '他者の助言の受入れ',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '自己・情緒',
                'title' => '他者の援助の受入れ',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '自己・情緒',
                'title' => '自己の目標を立てる',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '自己・情緒',
                'title' => '主体的に取り組む',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '自己・情緒',
                'title' => '就労への意識',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '動作・運動',
                'title' => '順番待ち',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '動作・運動',
                'title' => '動作模倣',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '動作・運動',
                'title' => '微細運動',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '動作・運動',
                'title' => '視線の活用',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '動作・運動',
                'title' => '苦手なことの克服',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '動作・運動',
                'title' => '粗大運動',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '動作・運動',
                'title' => 'ボールの操作',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '動作・運動',
                'title' => '身体感覚',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '動作・運動',
                'title' => '目と手の協応',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '動作・運動',
                'title' => '言語表現',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '動作・運動',
                'title' => '手指の巧緻性',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '動作・運動',
                'title' => '協応運動',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '動作・運動',
                'title' => 'ボディーイメージ',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '動作・運動',
                'title' => '道具の操作',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '動作・運動',
                'title' => '作業能力',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '動作・運動',
                'title' => '周りに合わせて動く',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '言語・認知',
                'title' => '因果関係の理解',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '言語・認知',
                'title' => '聴覚的理解',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '言語・認知',
                'title' => '概念形成',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '言語・認知',
                'title' => '言語理解',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '言語・認知',
                'title' => '地図理解',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '言語・認知',
                'title' => '言語概念',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '言語・認知',
                'title' => '勝ち負けの受入れ',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '言語・認知',
                'title' => '短期記憶',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '言語・認知',
                'title' => '矢印の意味理解',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '言語・認知',
                'title' => '空間認知',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '言語・認知',
                'title' => '行動理解',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '言語・認知',
                'title' => '対人的距離感',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '言語・認知',
                'title' => '役割理解',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '言語・認知',
                'title' => '想像力',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '言語・認知',
                'title' => '自己決定',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '言語・認知',
                'title' => '推理・推測',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '言語・認知',
                'title' => '対人意識',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '言語・認知',
                'title' => '非言語のやりとり',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '言語・認知',
                'title' => '質問する',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '言語・認知',
                'title' => '応答する',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '言語・認知',
                'title' => '推論する',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '言語・認知',
                'title' => '感情語の理解',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'kid_name' => '中山功太',
                'category' => '言語・認知',
                'title' => '対人的信頼感',
                'evaluation' => '◎',
                'teacher' => '佐藤',
                'detail' => '',
                'user_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ]

        ];
        # DB::table->insertでレコードの登録
        DB::table('memos')->insert($param);
    }
}
